#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/bin/sh

start_service() {
    procd_open_instance
    procd_set_param command /root/check_ip_riga.sh
    procd_set_param respawn 3600 # Run every 60 minutes (3600 seconds)
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "network"
}