#!/bin/sh /etc/rc.common

START=99
STOP=15

USE_PROCD=1
PROG=/bin/sh

hotspot_interface="radio0"

start_service() {
    procd_open_instance
    procd_set_param command $PROG -c '
cat << "EOF" | sh
        # Use an external script for SSID generation
        hotspot_ssid=$(sh /root/generate_ssid.sh)

        # Set the SSID once during start
        uci set wireless.default_radio0.ssid="$hotspot_ssid"
        uci commit wireless

        while true; do
            echo "Checking conditions at $(date)"
            
            current_status=$(uci get wireless.default_radio0.disabled)
            echo "Current WiFi status: $([ "$current_status" = "0" ] && echo "Enabled" || echo "Disabled")"

            if ping -c 1 8.8.8.8 >/dev/null 2>&1 && ndsctl json >/dev/null 2>&1; then
                echo "Internet and OpenNDS are available."
                if [ "$current_status" != "0" ]; then
                    echo "Turning on WiFi hotspot."
                    uci set wireless.default_radio0.disabled=0
                    uci commit wireless
                    wifi up
                else
                    echo "WiFi hotspot is already on."
                fi
            else
                echo "Internet or OpenNDS is not available."
                if [ "$current_status" != "1" ]; then
                    echo "Turning off WiFi hotspot."
                    uci set wireless.default_radio0.disabled=1
                    uci commit wireless
                    wifi down
                else
                    echo "WiFi hotspot is already off."
                fi
            fi
            
            sleep 60
        done
EOF
    '
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "network" "wireless"
}
